### ISSUE TITLE
DataSource properties?

### ISSUE THREAD

**Issue by spand** [JetBrains/exposed-intellij-plugin#3]
We configure our (Hikari)DataSource where we do something like this (for MariaDb):

```
hikariDataSource.addDataSourceProperty("sessionVariables", listOf(
        "character_set_client=utf8mb4",
        "character_set_results=utf8mb4",
        "character_set_connection=utf8mb4",
).joinToString())
```

We have not yet used this connection setup for DDL changes but I can image one might need this or something similar to override server defaults of charset for columns like VARCHAR etc.

**Comment by Tapac** [comment]
As plugin uses schemacrawler to get schema metadata and it doesn't support providing pre-setuped DataSource the only option is to add connectionProperties as a map. WIll be available in the next release
